<?
    $user_id = $this->post->user_id;
    $usersTable = new Zend_Db_Table('users');
    $user = $usersTable->find($user_id)->current();
?>
<div class="post">
    <h3><a href="/post/<?=$this->post->slug?>"><?=$this->post->title?></a></h3>
    <p class="timestamp">Posted: <?=date("n-d-Y H:i:s", $this->post->created_at)?> by <strong><?=$user->username?></strong></p>
    <p class="short-desc"><?=$this->post->short_description?></p>
    <p class="body"><?=$this->post->body?></p>
</div>